Repository aleximmer/Laplace, pull requests merged in 2024-07, with the labels that each got.

#202 Caveats
  .github/workflows/pytest.yml
  README.md
  laplace/baselaplace.py
  laplace/curvature/curvature.py
  tests/test_baselaplace.py
Labels: bug, documentation

#205 Add some checks in `optimize_prior_precision`
  README.md
  examples/huggingface_example.md
  laplace/baselaplace.py
Labels: documentation

#207 Add backend 'flowchart'
  README.md
  laplace/baselaplace.py
  laplace/lllaplace.py
Labels: documentation

#209 Update installation instruction
  README.md
Labels: documentation

#192 Functional Laplace Updated
  .github/workflows/pytest.yml
  .gitignore
  README.md
  examples/calibration_gp_example.md
  examples/calibration_gp_example.py
  examples/helper/util_gp.py
  examples/requirements.txt
  laplace/__init__.py
  laplace/baselaplace.py
  laplace/curvature/backpack.py
  laplace/curvature/curvature.py
  laplace/laplace.py
  laplace/lllaplace.py
  laplace/marglik_training.py
  laplace/utils/__init__.py
  laplace/utils/enums.py
  laplace/utils/utils.py
  tests/requirements.txt
  tests/test_functional_laplace.py
  tests/test_functional_laplace_unit.py
  tests/test_jacobians.py
  tests/test_serialization.py
  tests/utils.py
Labels: enhancement
