Repository aleximmer/Laplace, pull requests merged in 2024-06, with the labels that each got.

#167 Doc & example for reward modeling
  docs/baselaplace.html
  docs/curvature/curvature.html
  docs/curvature/index.html
  docs/index.html
  docs/regression_example.png
  docs/regression_example_online.png
  examples/helper/util.py
  examples/reward_modeling_example.md
  examples/reward_modeling_example.py
  laplace/__init__.py
  laplace/baselaplace.py
Labels: documentation

#170 Feature caching mechanism in LLLA
  examples/calibration_example.py
  examples/helper/dataloaders.py
  laplace/lllaplace.py
  laplace/utils/feature_extractor.py
  tests/test_lllaplace.py
Labels: enhancement

#173 Prevent computing posterior precision in KronLaplace when it's not fitted
  examples/huggingface_example.md
  examples/huggingface_example.py
  laplace/baselaplace.py
Labels: bug

#172 Add an option to reduce LLM features in `LLLaplace`
  examples/huggingface_example.md
  examples/huggingface_example.py
  laplace/lllaplace.py
  laplace/utils/feature_extractor.py
  tests/test_feature_extractor.py
  tests/test_lllaplace.py
Labels: enhancement

#176 Add `ruff check`, `ruff format --check`, and `pytest` Github actions
  .github/workflows/format-ruff.yml
  .github/workflows/lint-ruff.yml
  .github/workflows/pytest.yml
  README.md
  examples/bayesopt_example.py
  examples/calibration_example.md
  examples/calibration_example.py
  examples/helper/dataloaders.py
  examples/helper/util.py
  examples/helper/wideresnet.py
  examples/huggingface_example.md
  examples/huggingface_example.py
  examples/regression_example.md
  examples/regression_example.py
  examples/reward_modeling_example.md
  examples/reward_modeling_example.py
  laplace/__init__.py
  laplace/baselaplace.py
  laplace/curvature/__init__.py
  laplace/curvature/asdfghjkl.py
  laplace/curvature/asdl.py
  laplace/curvature/backpack.py
  laplace/curvature/curvature.py
  laplace/curvature/curvlinops.py
  laplace/laplace.py
  laplace/lllaplace.py
  laplace/marglik_training.py
  laplace/subnetlaplace.py
  laplace/utils/__init__.py
  laplace/utils/feature_extractor.py
  laplace/utils/matrix.py
  laplace/utils/metrics.py
  laplace/utils/subnetmask.py
  laplace/utils/swag.py
  laplace/utils/utils.py
  pyproject.toml
  tests/test_baselaplace.py
  tests/test_curv_backends_asdfghjkl.py
  tests/test_curv_backends_asdl.py
  tests/test_curv_backends_backpack.py
  tests/test_curv_backends_curvlinops.py
  tests/test_curv_backends_interface.py
  tests/test_feature_extractor.py
  tests/test_jacobians.py
  tests/test_laplace.py
  tests/test_lllaplace.py
  tests/test_matrix.py
  tests/test_metrics.py
  tests/test_serialization.py
  tests/test_subnetlaplace.py
  tests/test_subset_params.py
  tests/test_utils.py
  tests/utils.py
Labels: enhancement

#197 Remove depreciated `loss_average` argument of `KFACLinearOperator` and add makefile for ruff
  laplace/curvature/curvlinops.py
  makefile
  setup.cfg
Labels: bug, enhancement

#187 Use backend-native Jacobians if available
  laplace/baselaplace.py
  laplace/curvature/curvature.py
  tests/test_baselaplace.py
Labels: bug

#184 Update docs
  README.md
  docs/baselaplace.html
  docs/curvature/asdfghjkl.html
  docs/curvature/asdl.html
  docs/curvature/backpack.html
  docs/curvature/curvature.html
  docs/curvature/curvlinops.html
  docs/curvature/index.html
  docs/index.html
  docs/lllaplace.html
  docs/regression_example.png
  docs/regression_example_online.png
  docs/utils/feature_extractor.html
  docs/utils/index.html
  docs/utils/metrics.html
  docs/utils/utils.html
  examples/huggingface_example.md
  laplace/__init__.py
  laplace/utils/feature_extractor.py
Labels: documentation

#198 Add "Contributing" to the README
  README.md
Labels: documentation

#180 Typehinting
  examples/bayesopt_example.py
  laplace/__init__.py
  laplace/baselaplace.py
  laplace/curvature/asdfghjkl.py
  laplace/curvature/asdl.py
  laplace/curvature/backpack.py
  laplace/curvature/curvature.py
  laplace/curvature/curvlinops.py
  laplace/laplace.py
  laplace/lllaplace.py
  laplace/marglik_training.py
  laplace/subnetlaplace.py
  laplace/utils/__init__.py
  laplace/utils/enums.py
  laplace/utils/feature_extractor.py
  laplace/utils/matrix.py
  laplace/utils/metrics.py
  laplace/utils/subnetmask.py
  laplace/utils/swag.py
  laplace/utils/utils.py
  tests/test_baselaplace.py
  tests/test_lllaplace.py
  tests/test_subset_params.py
Labels: enhancement

#200 Refactor reward-modeling likelihood
  laplace/baselaplace.py
  laplace/utils/utils.py
Labels: enhancement

#199 Remove `try-except` from gridsearch
  laplace/baselaplace.py
  laplace/utils/utils.py
  tests/test_baselaplace.py
Labels: bug

#145 Add fast computation of functional_variance for DiagLLLaplace and KronLLLaplace
  laplace/baselaplace.py
  laplace/lllaplace.py
  laplace/utils/utils.py
  tests/test_baselaplace.py
  tests/test_lllaplace.py
Labels: enhancement
